export const communityCreations = [
  {
    id: 1,
    source: "/jerseys/black_jersey.png",
    name: "Midnight Edition",
    creator: "Alex",
    tags: ["Modern", "Bold"],
  },
  {
    id: 10,
    source: "/jerseys/noel_diwali.png",
    name: "Festive Flair",
    creator: "Noel",
    tags: ["Festive", "Elegant"],
  },
  {
    id: 2,
    source: "/jerseys/Classic_red_and_whit.png",
    name: "Classic Red",
    creator: "Maria",
    tags: ["Classic"],
  },
  {
    id: 6,
    source: "/jerseys/helloween_2.png",
    name: "Halloween Special",
    creator: "Liam",
    tags: ["Festive", "Bold"],
  },
  {
    id: 3,
    source: "/jerseys/Modern_blue_gradient.png",
    name: "Ocean Wave",
    creator: "João",
    tags: ["Modern", "Gradient"],
  },
  {
    id: 4,
    source: "/jerseys/Retro_90s_style_jers.png",
    name: "Retro Vibes",
    creator: "Carlos",
    tags: ["Retro", "Bold"],
  },
  {
    id: 11,
    source: "/jerseys/noel_helloween_2.png",
    name: "Ghostly Glow",
    creator: "Noel",
    tags: ["Festive", "Classic"],
  },
  {
    id: 16,
    source: "/jerseys/ronaldo.png",
    name: "Ronaldo Legacy",
    creator: "Cristiano",
    tags: ["Legend", "Classic"],
  },
  {
    id: 5,
    source: "/jerseys/hunyuan.png",
    name: "Nature's Touch",
    creator: "Sofia",
    tags: ["Nature-inspired", "Modern", "Futuristic"],
  },
  {
    id: 7,
    source: "/jerseys/velocity.png",
    name: "Velocity",
    creator: "Emma",
    tags: ["Modern", "Futuristic"],
  },
  {
    id: 8,
    source: "/jerseys/noel_helloween.png",
    name: "Spooky Night",
    creator: "Noel",
    tags: ["Festive", "Modern"],
  },
  {
    id: 9,
    source: "/jerseys/diwali.png",
    name: "Diwali Delight",
    creator: "Olivia",
    tags: ["Festive", "Elegant"],
  },
  // New images added below
  {
    id: 12,
    source: "/jerseys/base.png",
    name: "Foundation",
    creator: "Ava",
    tags: ["Minimal", "Classic"],
  },
  {
    id: 13,
    source: "/jerseys/ginni_red.jpg",
    name: "Ginni Red",
    creator: "Ginni",
    tags: ["Bold", "Classic"],
  },
  {
    id: 14,
    source: "/jerseys/imane_pink.jpg",
    name: "Imane Pink",
    creator: "Imane",
    tags: ["Modern", "Chic"],
  },
  {
    id: 15,
    source: "/jerseys/qatar.jpg",
    name: "Qatar Pride",
    creator: "Yousef",
    tags: ["National", "Elegant"],
  },
  {
    id: 17,
    source: "/jerseys/tm_ast-1997.jpeg",
    name: "AST 1997",
    creator: "Team AST",
    tags: ["Retro", "Team"],
  },
  {
    id: 18,
    source: "/jerseys/wendy_red.jpg",
    name: "Wendy Red",
    creator: "Wendy",
    tags: ["Bold", "Chic"],
  },
  // New batch: hk, space, xmas, halloween
  {
    id: 19,
    source: "/jerseys/hk_1.jpg",
    name: "Bayern Munich Dragon",
    creator: "Sam",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 20,
    source: "/jerseys/hk_2.jpg",
    name: "Bayern Munich Dragon 2",
    creator: "Jamie",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 21,
    source: "/jerseys/hk_3.jpg",
    name: "Bayern Munich Dragon 3",
    creator: "Taylor",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 22,
    source: "/jerseys/hk_4.jpg",
    name: "Bayern Munich Dragon 4",
    creator: "Morgan",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 23,
    source: "/jerseys/hk_5.jpg",
    name: "Bayern Munich Dragon 5",
    creator: "Jordan",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 24,
    source: "/jerseys/hk_6.jpg",
    name: "Bayern Munich Dragon 6",
    creator: "Casey",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 25,
    source: "/jerseys/hk_7.jpg",
    name: "Bayern Munich Dragon 7",
    creator: "Riley",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 26,
    source: "/jerseys/hk_8.jpg",
    name: "Bayern Munich Dragon 8",
    creator: "Drew",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  {
    id: 27,
    source: "/jerseys/hk_9.jpg",
    name: "Bayern Munich Dragon 9",
    creator: "Skyler",
    tags: ["Bayern Munich", "Chinese Dragon", "Special Edition"],
  },
  // Space edition Liverpool
  {
    id: 28,
    source: "/jerseys/space_1.jpg",
    name: "Space Liverpool 1",
    creator: "Alexis",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 29,
    source: "/jerseys/space_2.jpg",
    name: "Space Liverpool 2",
    creator: "Blake",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 30,
    source: "/jerseys/space_3.jpg",
    name: "Space Liverpool 3",
    creator: "Harper",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 31,
    source: "/jerseys/space_4.jpg",
    name: "Space Liverpool 4",
    creator: "Peyton",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 32,
    source: "/jerseys/space_5.jpg",
    name: "Space Liverpool 5",
    creator: "Quinn",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 33,
    source: "/jerseys/space_6.jpg",
    name: "Space Liverpool 6",
    creator: "Reese",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 34,
    source: "/jerseys/space_7.jpg",
    name: "Space Liverpool 7",
    creator: "Dakota",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 35,
    source: "/jerseys/space_8.jpg",
    name: "Space Liverpool 8",
    creator: "Avery",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 36,
    source: "/jerseys/space_9.jpg",
    name: "Space Liverpool 9",
    creator: "Finley",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 37,
    source: "/jerseys/space_10.jpg",
    name: "Space Liverpool 10",
    creator: "Hayden",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 38,
    source: "/jerseys/space_11.jpg",
    name: "Space Liverpool 11",
    creator: "Jesse",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 39,
    source: "/jerseys/space_12.jpg",
    name: "Space Liverpool 12",
    creator: "Kendall",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 40,
    source: "/jerseys/space_13.jpg",
    name: "Space Liverpool 13",
    creator: "Logan",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 41,
    source: "/jerseys/space_14.jpg",
    name: "Space Liverpool 14",
    creator: "Milan",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 42,
    source: "/jerseys/space_15.jpg",
    name: "Space Liverpool 15",
    creator: "Nico",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 43,
    source: "/jerseys/space_16.jpg",
    name: "Space Liverpool 16",
    creator: "Oakley",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 44,
    source: "/jerseys/space_17.jpg",
    name: "Space Liverpool 17",
    creator: "Parker",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 45,
    source: "/jerseys/space_18.jpg",
    name: "Space Liverpool 18",
    creator: "Remy",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 46,
    source: "/jerseys/space_19.jpg",
    name: "Space Liverpool 19",
    creator: "Sage",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 47,
    source: "/jerseys/space_20.jpg",
    name: "Space Liverpool 20",
    creator: "Tatum",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  {
    id: 48,
    source: "/jerseys/space_21.jpg",
    name: "Space Liverpool 21",
    creator: "Val",
    tags: ["Liverpool", "Space Edition", "Futuristic"],
  },
  // Xmas edition Barcelona
  {
    id: 49,
    source: "/jerseys/xmas_1.jpg",
    name: "Xmas Barcelona 1",
    creator: "Wren",
    tags: ["Barcelona", "Christmas Edition", "Festive"],
  },
  {
    id: 50,
    source: "/jerseys/xmas_2.jpg",
    name: "Xmas Barcelona 2",
    creator: "Zion",
    tags: ["Barcelona", "Christmas Edition", "Festive"],
  },
  {
    id: 51,
    source: "/jerseys/xmas_3.jpg",
    name: "Xmas Barcelona 3",
    creator: "River",
    tags: ["Barcelona", "Christmas Edition", "Festive"],
  },
  {
    id: 52,
    source: "/jerseys/xmas_4.jpg",
    name: "Xmas Barcelona 4",
    creator: "Sasha",
    tags: ["Barcelona", "Christmas Edition", "Festive"],
  },
  {
    id: 53,
    source: "/jerseys/xmas_5.jpg",
    name: "Xmas Barcelona 5",
    creator: "Teagan",
    tags: ["Barcelona", "Christmas Edition", "Festive"],
  },
  {
    id: 54,
    source: "/jerseys/xmas_6.jpg",
    name: "Xmas Barcelona 6",
    creator: "Winter",
    tags: ["Barcelona", "Christmas Edition", "Festive"],
  },
  // Halloween edition Real Madrid
  {
    id: 55,
    source: "/jerseys/halloween_1.jpg",
    name: "Halloween Real Madrid 1",
    creator: "Arden",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 56,
    source: "/jerseys/halloween_2.jpg",
    name: "Halloween Real Madrid 2",
    creator: "Briar",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 57,
    source: "/jerseys/halloween_3.jpg",
    name: "Halloween Real Madrid 3",
    creator: "Cleo",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 58,
    source: "/jerseys/halloween_4.jpg",
    name: "Halloween Real Madrid 4",
    creator: "Dove",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 59,
    source: "/jerseys/halloween_5.jpg",
    name: "Halloween Real Madrid 5",
    creator: "Echo",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 60,
    source: "/jerseys/halloween_6.jpg",
    name: "Halloween Real Madrid 6",
    creator: "Fable",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 61,
    source: "/jerseys/halloween_7.jpg",
    name: "Halloween Real Madrid 7",
    creator: "Gale",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 62,
    source: "/jerseys/halloween_8.jpg",
    name: "Halloween Real Madrid 8",
    creator: "Hollis",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 63,
    source: "/jerseys/halloween_9.jpg",
    name: "Halloween Real Madrid 9",
    creator: "Indigo",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
  {
    id: 64,
    source: "/jerseys/halloween_10.jpg",
    name: "Halloween Real Madrid 10",
    creator: "Jules",
    tags: ["Real Madrid", "Halloween Edition", "Spooky"],
  },
];
