export const communityCreations = [
  {
    id: 1,
    source: "/jerseys/black_jersey.png",
    name: "Midnight Edition",
    creator: "Alex",
    tags: ["Modern", "Bold"],
  },
  {
    id: 10,
    source: "/jerseys/noel_diwali.png",
    name: "Festive Flair",
    creator: "Noel",
    tags: ["Festive", "Elegant"],
  },
  {
    id: 2,
    source: "/jerseys/Classic_red_and_whit.png",
    name: "Classic Red",
    creator: "Maria",
    tags: ["Classic"],
  },
  {
    id: 6,
    source: "/jerseys/helloween_2.png",
    name: "Halloween Special",
    creator: "Liam",
    tags: ["Festive", "Bold"],
  },
  {
    id: 3,
    source: "/jerseys/Modern_blue_gradient.png",
    name: "Ocean Wave",
    creator: "João",
    tags: ["Modern"],
  },
  {
    id: 4,
    source: "/jerseys/Retro_90s_style_jers.png",
    name: "Retro Vibes",
    creator: "Carlos",
    tags: ["Retro", "Bold"],
  },
  {
    id: 11,
    source: "/jerseys/noel_helloween_2.png",
    name: "Ghostly Glow",
    creator: "Noel",
    tags: ["Festive", "Classic"],
  },
  {
    id: 5,
    source: "/jerseys/hunyuan.png",
    name: "Nature's Touch",
    creator: "Sofia",
    tags: ["Modern", "Futuristic"],
  },
  {
    id: 7,
    source: "/jerseys/velocity.png",
    name: "Velocity",
    creator: "Emma",
    tags: ["Modern", "Futuristic"],
  },
  {
    id: 8,
    source: "/jerseys/noel_helloween.png",
    name: "Spooky Night",
    creator: "Noel",
    tags: ["Festive", "Modern"],
  },
  {
    id: 9,
    source: "/jerseys/diwali.png",
    name: "Diwali Delight",
    creator: "Olivia",
    tags: ["Festive", "Elegant"],
  },
];
