export const communityCreations = [
  {
    id: 1,
    source: "/jerseys/black_jersey.png",
    name: "Midnight Edition",
    creator: "Alex",
    tags: ["Modern", "Bold"],
  },
  {
    id: 10,
    source: "/jerseys/noel_diwali.png",
    name: "Festive Flair",
    creator: "Noel",
    tags: ["Festive", "Elegant"],
  },
  {
    id: 2,
    source: "/jerseys/Classic_red_and_whit.png",
    name: "Classic Red",
    creator: "Maria",
    tags: ["Classic"],
  },
  {
    id: 6,
    source: "/jerseys/helloween_2.png",
    name: "Halloween Special",
    creator: "Liam",
    tags: ["Festive", "Bold"],
  },
  {
    id: 3,
    source: "/jerseys/Modern_blue_gradient.png",
    name: "Ocean Wave",
    creator: "João",
    tags: ["Modern", "Gradient"],
  },
  {
    id: 4,
    source: "/jerseys/Retro_90s_style_jers.png",
    name: "Retro Vibes",
    creator: "Carlos",
    tags: ["Retro", "Bold"],
  },
  {
    id: 11,
    source: "/jerseys/noel_helloween_2.png",
    name: "Ghostly Glow",
    creator: "Noel",
    tags: ["Festive", "Classic"],
  },
  {
    id: 16,
    source: "/jerseys/ronaldo.png",
    name: "Ronaldo Legacy",
    creator: "Cristiano",
    tags: ["Legend", "Classic"],
  },
  {
    id: 5,
    source: "/jerseys/hunyuan.png",
    name: "Nature's Touch",
    creator: "Sofia",
    tags: ["Nature-inspired", "Modern", "Futuristic"],
  },
  {
    id: 7,
    source: "/jerseys/velocity.png",
    name: "Velocity",
    creator: "Emma",
    tags: ["Modern", "Futuristic"],
  },
  {
    id: 8,
    source: "/jerseys/noel_helloween.png",
    name: "Spooky Night",
    creator: "Noel",
    tags: ["Festive", "Modern"],
  },
  {
    id: 9,
    source: "/jerseys/diwali.png",
    name: "Diwali Delight",
    creator: "Olivia",
    tags: ["Festive", "Elegant"],
  },
  // New images added below
  {
    id: 12,
    source: "/jerseys/base.png",
    name: "Foundation",
    creator: "Ava",
    tags: ["Minimal", "Classic"],
  },
  {
    id: 13,
    source: "/jerseys/ginni_red.jpg",
    name: "Ginni Red",
    creator: "Ginni",
    tags: ["Bold", "Classic"],
  },
  {
    id: 14,
    source: "/jerseys/imane_pink.jpg",
    name: "Imane Pink",
    creator: "Imane",
    tags: ["Modern", "Chic"],
  },
  {
    id: 15,
    source: "/jerseys/qatar.jpg",
    name: "Qatar Pride",
    creator: "Yousef",
    tags: ["National", "Elegant"],
  },
  {
    id: 17,
    source: "/jerseys/tm_ast-1997.jpeg",
    name: "AST 1997",
    creator: "Team AST",
    tags: ["Retro", "Team"],
  },
  {
    id: 18,
    source: "/jerseys/wendy_red.jpg",
    name: "Wendy Red",
    creator: "Wendy",
    tags: ["Bold", "Chic"],
  },
];
