import type { Team } from "../teams";

export const austriaBundesliga: Team[] = [
  {
    id: "austria-vienna",
    name: "Austria Vienna",
    primaryColor: "#FF6600",
    secondaryColor: "#000000",
    league: "Austria Bundesliga",
    logo: "@/public/logos/Austria - Bundesliga/Austria Vienna.png",
  },
  {
    id: "blau-weiss-linz",
    name: "FC Blau-Weiss Linz",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/FC Blau-Weiss Linz.png",
  },
  {
    id: "grazer-ak",
    name: "Grazer AK 1902",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/Grazer AK 1902.png",
  },
  {
    id: "lask",
    name: "LASK",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/LASK.png",
  },
  {
    id: "rapid-vienna",
    name: "Rapid Vienna",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/Rapid Vienna.png",
  },
  {
    id: "red-bull-salzburg",
    name: "Red Bull Salzburg",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/Red Bull Salzburg.png",
  },
  {
    id: "scr-altach",
    name: "SCR Altach",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/SCR Altach.png",
  },
  {
    id: "sk-sturm-graz",
    name: "SK Sturm Graz",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/SK Sturm Graz.png",
  },
  {
    id: "sv-ried",
    name: "SV Ried",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/SV Ried.png",
  },
  {
    id: "tsv-hartberg",
    name: "TSV Hartberg",
    primaryColor: "#FF6600",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/TSV Hartberg.png",
  },
  {
    id: "wolfsberger-ac",
    name: "Wolfsberger AC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/Wolfsberger AC.png",
  },
  {
    id: "wsg-tirol",
    name: "WSG Tirol",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Austria Bundesliga",
    logo: "@/assets/logos/Austria - Bundesliga/WSG Tirol.png",
  },
];
