import type { Team } from "../teams";

export const belgiumJupilerProLeague: Team[] = [
  {
    id: "cercle-brugge",
    name: "Cercle Brugge",
    primaryColor: "#00AA00",
    secondaryColor: "#000000",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Cercle Brugge.png",
  },
  {
    id: "club-brugge",
    name: "Club Brugge KV",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Club Brugge KV.png",
  },
  {
    id: "fcv-dender",
    name: "FCV Dender EH",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/FCV Dender EH.png",
  },
  {
    id: "kaa-gent",
    name: "KAA Gent",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/KAA Gent.png",
  },
  {
    id: "krc-genk",
    name: "KRC Genk",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/KRC Genk.png",
  },
  {
    id: "kv-mechelen",
    name: "KV Mechelen",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/KV Mechelen.png",
  },
  {
    id: "kvc-westerlo",
    name: "KVC Westerlo",
    primaryColor: "#CC0000",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/KVC Westerlo.png",
  },
  {
    id: "ohl-leuven",
    name: "Oud-Heverlee Leuven",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Oud-Heverlee Leuven.png",
  },
  {
    id: "raal-la-louviere",
    name: "RAAL La Louvière",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/RAAL La Louvière.png",
  },
  {
    id: "antwerp",
    name: "Royal Antwerp FC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Royal Antwerp FC.png",
  },
  {
    id: "charleroi",
    name: "Royal Charleroi SC",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Royal Charleroi SC.png",
  },
  {
    id: "rsc-anderlecht",
    name: "RSC Anderlecht",
    primaryColor: "#9900FF",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/RSC Anderlecht.png",
  },
  {
    id: "st-truidense",
    name: "Sint-Truidense VV",
    primaryColor: "#FFFF00",
    secondaryColor: "#000000",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Sint-Truidense VV.png",
  },
  {
    id: "standard-liege",
    name: "Standard Liège",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Standard Liège.png",
  },
  {
    id: "union-sg",
    name: "Union Saint-Gilloise",
    primaryColor: "#FFFF00",
    secondaryColor: "#000000",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Union Saint-Gilloise.png",
  },
  {
    id: "zulte-waregem",
    name: "Zulte Waregem",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Belgium Jupiler Pro League",
    logo: "@/assets/logos/Belgium - Jupiler Pro League/Zulte Waregem.png",
  },
];
