import type { Team } from "../teams";

export const bulgariaEfbetLiga: Team[] = [
  {
    id: "arda-kardzhali",
    name: "Arda Kardzhali",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Arda Kardzhali.png",
  },
  {
    id: "beroe-stara-zagora",
    name: "Beroe Stara Zagora",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Beroe Stara Zagora.png",
  },
  {
    id: "botev-plovdiv",
    name: "Botev Plovdiv",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Botev Plovdiv.png",
  },
  {
    id: "botev-vratsa",
    name: "Botev Vratsa",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Botev Vratsa.png",
  },
  {
    id: "cherno-more-varna",
    name: "Cherno More Varna",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Cherno More Varna.png",
  },
  {
    id: "cska-1948",
    name: "CSKA 1948",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/CSKA 1948.png",
  },
  {
    id: "cska-sofia",
    name: "CSKA-Sofia",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/CSKA-Sofia.png",
  },
  {
    id: "dobrudzha-dobrich",
    name: "Dobrudzha Dobrich",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Dobrudzha Dobrich.png",
  },
  {
    id: "levski-sofia",
    name: "Levski Sofia",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Levski Sofia.png",
  },
  {
    id: "lokomotiv-plovdiv",
    name: "Lokomotiv Plovdiv",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Lokomotiv Plovdiv.png",
  },
  {
    id: "lokomotiv-sofia",
    name: "Lokomotiv Sofia",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Lokomotiv Sofia.png",
  },
  {
    id: "ludogorets-razgrad",
    name: "Ludogorets Razgrad",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Ludogorets Razgrad.png",
  },
  {
    id: "montana",
    name: "Montana",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Montana.png",
  },
  {
    id: "septemvri-sofia",
    name: "Septemvri Sofia",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Septemvri Sofia.png",
  },
  {
    id: "slavia-sofia",
    name: "Slavia Sofia",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Slavia Sofia.png",
  },
  {
    id: "spartak-varna",
    name: "Spartak Varna",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Bulgaria efbet Liga",
    logo: "/logos/Bulgaria - efbet Liga/Spartak Varna.png",
  },
];
