import type { Team } from "../teams";

export const croatiaSuperSportHnl: Team[] = [
  {
    id: "dinamo-zagreb",
    name: "GNK Dinamo Zagreb",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/GNK Dinamo Zagreb.png",
  },
  {
    id: "hnk-gorica",
    name: "HNK Gorica",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/HNK Gorica.png",
  },
  {
    id: "hajduk-split",
    name: "HNK Hajduk Split",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/HNK Hajduk Split.png",
  },
  {
    id: "hnk-rijeka",
    name: "HNK Rijeka",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066FF",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/HNK Rijeka.png",
  },
  {
    id: "hnk-vukovar",
    name: "HNK Vukovar 1991",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/HNK Vukovar 1991.png",
  },
  {
    id: "nk-istra-1961",
    name: "NK Istra 1961",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/NK Istra 1961.png",
  },
  {
    id: "nk-lokomotiva-zagreb",
    name: "NK Lokomotiva Zagreb",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/NK Lokomotiva Zagreb.png",
  },
  {
    id: "nk-osijek",
    name: "NK Osijek",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/NK Osijek.png",
  },
  {
    id: "nk-varazdin",
    name: "NK Varazdin",
    primaryColor: "#FFFF00",
    secondaryColor: "#000000",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/NK Varazdin.png",
  },
  {
    id: "slaven-belupo",
    name: "Slaven Belupo Koprivnica",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Croatia SuperSport HNL",
    logo: "@/assets/logos/Croatia - SuperSport HNL/Slaven Belupo Koprivnica.png",
  },
];
