import type { Team } from "../teams";

export const czechRepublicChanceLiga: Team[] = [
  {
    id: "fc-slovacko",
    name: "1.FC Slovacko",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/1.FC Slovacko.png",
  },
  {
    id: "sparta-prague",
    name: "AC Sparta Prague",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/AC Sparta Prague.png",
  },
  {
    id: "bohemians-prague",
    name: "Bohemians Prague 1905",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/Bohemians Prague 1905.png",
  },
  {
    id: "fc-banik-ostrava",
    name: "FC Banik Ostrava",
    primaryColor: "#FF0000",
    secondaryColor: "#000000",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FC Banik Ostrava.png",
  },
  {
    id: "fc-hradec-kralove",
    name: "FC Hradec Kralove",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FC Hradec Kralove.png",
  },
  {
    id: "fc-slovan-liberec",
    name: "FC Slovan Liberec",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF6600",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FC Slovan Liberec.png",
  },
  {
    id: "fc-viktoria-plzen",
    name: "FC Viktoria Plzen",
    primaryColor: "#0066CC",
    secondaryColor: "#FF0000",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FC Viktoria Plzen.png",
  },
  {
    id: "fc-zlin",
    name: "FC Zlin",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FC Zlin.png",
  },
  {
    id: "fk-dukla-prague",
    name: "FK Dukla Prague",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FK Dukla Prague.png",
  },
  {
    id: "fk-jablonec",
    name: "FK Jablonec",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FK Jablonec.png",
  },
  {
    id: "fk-mlada-boleslav",
    name: "FK Mlada Boleslav",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FK Mlada Boleslav.png",
  },
  {
    id: "fk-pardubice",
    name: "FK Pardubice",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FK Pardubice.png",
  },
  {
    id: "fk-teplice",
    name: "FK Teplice",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/FK Teplice.png",
  },
  {
    id: "mfk-karvina",
    name: "MFK Karvina",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/MFK Karvina.png",
  },
  {
    id: "sk-sigma-olomouc",
    name: "SK Sigma Olomouc",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/SK Sigma Olomouc.png",
  },
  {
    id: "sk-slavia-prague",
    name: "SK Slavia Prague",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Czech Republic Chance Liga",
    logo: "@/assets/logos/Czech Republic - Chance Liga/SK Slavia Prague.png",
  },
];
