import type { Team } from "../teams";

export const denmarkSuperliga: Team[] = [
  {
    id: "aarhus-gf",
    name: "Aarhus GF",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Aarhus GF.png",
  },
  {
    id: "brondby-if",
    name: "Bröndby IF",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Bröndby IF.png",
  },
  {
    id: "fc-copenhagen",
    name: "FC Copenhagen",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/FC Copenhagen.png",
  },
  {
    id: "fc-fredericia",
    name: "FC Fredericia",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/FC Fredericia.png",
  },
  {
    id: "fc-midtjylland",
    name: "FC Midtjylland",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/FC Midtjylland.png",
  },
  {
    id: "fc-nordsjaelland",
    name: "FC Nordsjaelland",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/FC Nordsjaelland.png",
  },
  {
    id: "odense-boldklub",
    name: "Odense Boldklub",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Odense Boldklub.png",
  },
  {
    id: "randers-fc",
    name: "Randers FC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Randers FC.png",
  },
  {
    id: "silkeborg-if",
    name: "Silkeborg IF",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Silkeborg IF.png",
  },
  {
    id: "sonderjyske",
    name: "Sönderjyske",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Sönderjyske.png",
  },
  {
    id: "vejle-boldklub",
    name: "Vejle Boldklub",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Vejle Boldklub.png",
  },
  {
    id: "viborg-ff",
    name: "Viborg FF",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Denmark Superliga",
    logo: "/logos/Denmark - Superliga/Viborg FF.png",
  },
];
