import type { Team } from "../teams";

export const englandPremierLeague: Team[] = [
  {
    id: "afc-bournemouth",
    name: "AFC Bournemouth",
    primaryColor: "#FF0000",
    secondaryColor: "#000000",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/AFC Bournemouth.png",
  },
  {
    id: "arsenal",
    name: "Arsenal FC",
    primaryColor: "#EF0107",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Arsenal FC.png",
  },
  {
    id: "aston-villa",
    name: "Aston Villa",
    primaryColor: "#0B3161",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Aston Villa.png",
  },
  {
    id: "brentford",
    name: "Brentford FC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Brentford FC.png",
  },
  {
    id: "brighton",
    name: "Brighton & Hove Albion",
    primaryColor: "#0054B4",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Brighton & Hove Albion.png",
  },
  {
    id: "burnley",
    name: "Burnley FC",
    primaryColor: "#6B4A97",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Burnley FC.png",
  },
  {
    id: "chelsea",
    name: "Chelsea FC",
    primaryColor: "#034694",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Chelsea FC.png",
  },
  {
    id: "crystal-palace",
    name: "Crystal Palace",
    primaryColor: "#1B50BE",
    secondaryColor: "#FF0000",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Crystal Palace.png",
  },
  {
    id: "everton",
    name: "Everton FC",
    primaryColor: "#003399",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Everton FC.png",
  },
  {
    id: "fulham",
    name: "Fulham FC",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Fulham FC.png",
  },
  {
    id: "leeds-united",
    name: "Leeds United",
    primaryColor: "#FFFFFF",
    secondaryColor: "#1D428A",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Leeds United.png",
  },
  {
    id: "liverpool",
    name: "Liverpool FC",
    primaryColor: "#C8102E",
    secondaryColor: "#00B2A9",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Liverpool FC.png",
  },
  {
    id: "man-city",
    name: "Manchester City",
    primaryColor: "#6CABDD",
    secondaryColor: "#1C2C5B",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Manchester City.png",
  },
  {
    id: "man-united",
    name: "Manchester United",
    primaryColor: "#DA291C",
    secondaryColor: "#FBE122",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Manchester United.png",
  },
  {
    id: "newcastle",
    name: "Newcastle United",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Newcastle United.png",
  },
  {
    id: "nottingham-forest",
    name: "Nottingham Forest",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Nottingham Forest.png",
  },
  {
    id: "sunderland",
    name: "Sunderland AFC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Sunderland AFC.png",
  },
  {
    id: "tottenham",
    name: "Tottenham Hotspur",
    primaryColor: "#FFFFFF",
    secondaryColor: "#132257",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Tottenham Hotspur.png",
  },
  {
    id: "west-ham",
    name: "West Ham United",
    primaryColor: "#7A263A",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/West Ham United.png",
  },
  {
    id: "wolverhampton",
    name: "Wolverhampton Wanderers",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Premier League",
    logo: "@/assets/logos/England - Premier League/Wolverhampton Wanderers.png",
  },
];
