import type { Team } from "../teams";

export const franceLigue1: Team[] = [
  {
    id: "aj-auxerre",
    name: "AJ Auxerre",
    primaryColor: "#FFFFFF",
    secondaryColor: "#006600",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/AJ Auxerre.png",
  },
  {
    id: "angers-sco",
    name: "Angers SCO",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Angers SCO.png",
  },
  {
    id: "monaco",
    name: "AS Monaco",
    primaryColor: "#ED1C24",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/AS Monaco.png",
  },
  {
    id: "fc-lorient",
    name: "FC Lorient",
    primaryColor: "#FF6600",
    secondaryColor: "#000000",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/FC Lorient.png",
  },
  {
    id: "fc-metz",
    name: "FC Metz",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/FC Metz.png",
  },
  {
    id: "fc-nantes",
    name: "FC Nantes",
    primaryColor: "#FFDC00",
    secondaryColor: "#019B3E",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/FC Nantes.png",
  },
  {
    id: "fc-toulouse",
    name: "FC Toulouse",
    primaryColor: "#FFFFFF",
    secondaryColor: "#8B3030",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/FC Toulouse.png",
  },
  {
    id: "le-havre-ac",
    name: "Le Havre AC",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Le Havre AC.png",
  },
  {
    id: "lille",
    name: "LOSC Lille",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/LOSC Lille.png",
  },
  {
    id: "nice",
    name: "OGC Nice",
    primaryColor: "#C91B2E",
    secondaryColor: "#000000",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/OGC Nice.png",
  },
  {
    id: "lyon",
    name: "Olympique Lyon",
    primaryColor: "#FFFFFF",
    secondaryColor: "#1B3F8F",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Olympique Lyon.png",
  },
  {
    id: "marseille",
    name: "Olympique Marseille",
    primaryColor: "#2FAEE0",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Olympique Marseille.png",
  },
  {
    id: "paris-fc",
    name: "Paris FC",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Paris FC.png",
  },
  {
    id: "psg",
    name: "Paris Saint-Germain",
    primaryColor: "#004170",
    secondaryColor: "#DA291C",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Paris Saint-Germain.png",
  },
  {
    id: "rc-lens",
    name: "RC Lens",
    primaryColor: "#FDB913",
    secondaryColor: "#000000",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/RC Lens.png",
  },
  {
    id: "rc-strasbourg",
    name: "RC Strasbourg Alsace",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/RC Strasbourg Alsace.png",
  },
  {
    id: "stade-brestois",
    name: "Stade Brestois 29",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Stade Brestois 29.png",
  },
  {
    id: "rennes",
    name: "Stade Rennais FC",
    primaryColor: "#C81828",
    secondaryColor: "#000000",
    league: "France Ligue 1",
    logo: "@/assets/logos/France - Ligue 1/Stade Rennais FC.png",
  },
];
