import type { Team } from "../teams";

export const germanyBundesliga: Team[] = [
  {
    id: "heidenheim",
    name: "1.FC Heidenheim 1846",
    primaryColor: "#CC0000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/1.FC Heidenheim 1846.png",
  },
  {
    id: "fc-koln",
    name: "1.FC Köln",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/1.FC Köln.png",
  },
  {
    id: "union-berlin",
    name: "1.FC Union Berlin",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/1.FC Union Berlin.png",
  },
  {
    id: "mainz-05",
    name: "1.FSV Mainz 05",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/1.FSV Mainz 05.png",
  },
  {
    id: "leverkusen",
    name: "Bayer 04 Leverkusen",
    primaryColor: "#E32221",
    secondaryColor: "#000000",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/Bayer 04 Leverkusen.png",
  },
  {
    id: "bayern",
    name: "Bayern Munich",
    primaryColor: "#DC052D",
    secondaryColor: "#0066B2",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/Bayern Munich.png",
  },
  {
    id: "dortmund",
    name: "Borussia Dortmund",
    primaryColor: "#FDE100",
    secondaryColor: "#000000",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/Borussia Dortmund.png",
  },
  {
    id: "borussia-monchengladbach",
    name: "Borussia Mönchengladbach",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/Borussia Mönchengladbach.png",
  },
  {
    id: "frankfurt",
    name: "Eintracht Frankfurt",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/Eintracht Frankfurt.png",
  },
  {
    id: "augsburg",
    name: "FC Augsburg",
    primaryColor: "#BA0021",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/FC Augsburg.png",
  },
  {
    id: "fc-st-pauli",
    name: "FC St. Pauli",
    primaryColor: "#8B0000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/FC St. Pauli.png",
  },
  {
    id: "hamburg-sv",
    name: "Hamburger SV",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/Hamburger SV.png",
  },
  {
    id: "rb-leipzig",
    name: "RB Leipzig",
    primaryColor: "#DD0741",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/RB Leipzig.png",
  },
  {
    id: "freiburg",
    name: "SC Freiburg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/SC Freiburg.png",
  },
  {
    id: "werder-bremen",
    name: "SV Werder Bremen",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/SV Werder Bremen.png",
  },
  {
    id: "hoffenheim",
    name: "TSG 1899 Hoffenheim",
    primaryColor: "#1C4DB7",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/TSG 1899 Hoffenheim.png",
  },
  {
    id: "vfb-stuttgart",
    name: "VfB Stuttgart",
    primaryColor: "#FFFFFF",
    secondaryColor: "#C40C2E",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/VfB Stuttgart.png",
  },
  {
    id: "wolfsburg",
    name: "VfL Wolfsburg",
    primaryColor: "#37B959",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: "@/assets/logos/Germany - Bundesliga/VfL Wolfsburg.png",
  },
];
