import type { Team } from "../teams";

export const greeceSuperLeague1: Team[] = [
  {
    id: "ae-kifisias",
    name: "AE Kifisias",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/AE Kifisias.png",
  },
  {
    id: "ae-larisa",
    name: "AE Larisa",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/AE Larisa.png",
  },
  {
    id: "aek-athens",
    name: "AEK Athens",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/AEK Athens.png",
  },
  {
    id: "apo-levadiakos",
    name: "APO Levadiakos",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/APO Levadiakos.png",
  },
  {
    id: "aris-thessaloniki",
    name: "Aris Thessaloniki",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Aris Thessaloniki.png",
  },
  {
    id: "asteras-aktor",
    name: "Asteras Aktor",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Asteras Aktor.png",
  },
  {
    id: "atromitos-athens",
    name: "Atromitos Athens",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Atromitos Athens.png",
  },
  {
    id: "ofi-crete",
    name: "OFI Crete FC",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/OFI Crete FC.png",
  },
  {
    id: "olympiacos",
    name: "Olympiacos Piraeus",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Olympiacos Piraeus.png",
  },
  {
    id: "panathinaikos",
    name: "Panathinaikos FC",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Panathinaikos FC.png",
  },
  {
    id: "panetolikos",
    name: "Panetolikos GFS",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Panetolikos GFS.png",
  },
  {
    id: "panserraikos",
    name: "Panserraikos",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Panserraikos.png",
  },
  {
    id: "paok-thessaloniki",
    name: "PAOK Thessaloniki",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/PAOK Thessaloniki.png",
  },
  {
    id: "volos-nps",
    name: "Volos NPS",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Greece Super League 1",
    logo: "@/assets/logos/Greece - Super League 1/Volos NPS.png",
  },
];
