import type { Team } from "../teams";

export const israelLigatHaAl: Team[] = [
  {
    id: "beitar-jerusalem",
    name: "Beitar Jerusalem",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Beitar Jerusalem.png",
  },
  {
    id: "fc-ashdod",
    name: "FC Ashdod",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/FC Ashdod.png",
  },
  {
    id: "hapoel-beer-sheva",
    name: "Hapoel Beer Sheva",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Hapoel Beer Sheva.png",
  },
  {
    id: "hapoel-haifa",
    name: "Hapoel Haifa",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Hapoel Haifa.png",
  },
  {
    id: "hapoel-jerusalem",
    name: "Hapoel Jerusalem",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Hapoel Jerusalem.png",
  },
  {
    id: "hapoel-petah-tikva",
    name: "Hapoel Petah Tikva",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Hapoel Petah Tikva.png",
  },
  {
    id: "hapoel-tel-aviv",
    name: "Hapoel Tel Aviv",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Hapoel Tel Aviv.png",
  },
  {
    id: "ihud-bnei-sakhnin",
    name: "Ihud Bnei Sakhnin",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Ihud Bnei Sakhnin.png",
  },
  {
    id: "ironi-kiryat-shmona",
    name: "Ironi Kiryat Shmona",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Ironi Kiryat Shmona.png",
  },
  {
    id: "ironi-tiberias",
    name: "Ironi Tiberias",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Ironi Tiberias.png",
  },
  {
    id: "maccabi-bnei-reineh",
    name: "Maccabi Bnei Reineh",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Maccabi Bnei Reineh.png",
  },
  {
    id: "maccabi-haifa",
    name: "Maccabi Haifa",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Maccabi Haifa.png",
  },
  {
    id: "maccabi-netanya",
    name: "Maccabi Netanya",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Maccabi Netanya.png",
  },
  {
    id: "maccabi-tel-aviv",
    name: "Maccabi Tel Aviv",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Israel Ligat ha'Al",
    logo: "/logos/Israel - Ligat ha'Al/Maccabi Tel Aviv.png",
  },
];
