import type { Team } from "../teams";

export const italySerieA: Team[] = [
  {
    id: "ac-milan",
    name: "AC Milan",
    primaryColor: "#FB090B",
    secondaryColor: "#000000",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/AC Milan.png",
  },
  {
    id: "fiorentina",
    name: "ACF Fiorentina",
    primaryColor: "#800080",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/ACF Fiorentina.png",
  },
  {
    id: "roma",
    name: "AS Roma",
    primaryColor: "#8E1F2F",
    secondaryColor: "#F0BC42",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/AS Roma.png",
  },
  {
    id: "atalanta",
    name: "Atalanta BC",
    primaryColor: "#000000",
    secondaryColor: "#0066FF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Atalanta BC.png",
  },
  {
    id: "bologna",
    name: "Bologna FC 1909",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Bologna FC 1909.png",
  },
  {
    id: "cagliari",
    name: "Cagliari Calcio",
    primaryColor: "#FF0000",
    secondaryColor: "#0066CC",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Cagliari Calcio.png",
  },
  {
    id: "como",
    name: "Como 1907",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Como 1907.png",
  },
  {
    id: "genoa",
    name: "Genoa CFC",
    primaryColor: "#FF0000",
    secondaryColor: "#0066CC",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Genoa CFC.png",
  },
  {
    id: "hellas-verona",
    name: "Hellas Verona",
    primaryColor: "#FFD700",
    secondaryColor: "#0066FF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Hellas Verona.png",
  },
  {
    id: "inter",
    name: "Inter Milan",
    primaryColor: "#010E80",
    secondaryColor: "#000000",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Inter Milan.png",
  },
  {
    id: "juventus",
    name: "Juventus FC",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Juventus FC.png",
  },
  {
    id: "parma",
    name: "Parma Calcio 1913",
    primaryColor: "#FFD700",
    secondaryColor: "#0066CC",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Parma Calcio 1913.png",
  },
  {
    id: "pisa",
    name: "Pisa Sporting Club",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Pisa Sporting Club.png",
  },
  {
    id: "lazio",
    name: "SS Lazio",
    primaryColor: "#002299",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/SS Lazio.png",
  },
  {
    id: "napoli",
    name: "SSC Napoli",
    primaryColor: "#12A0D7",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/SSC Napoli.png",
  },
  {
    id: "torino",
    name: "Torino FC",
    primaryColor: "#8B0000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Torino FC.png",
  },
  {
    id: "udinese",
    name: "Udinese Calcio",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/Udinese Calcio.png",
  },
  {
    id: "cremonese",
    name: "US Cremonese",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/US Cremonese.png",
  },
  {
    id: "lecce",
    name: "US Lecce",
    primaryColor: "#FFD700",
    secondaryColor: "#FF0000",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/US Lecce.png",
  },
  {
    id: "sassuolo",
    name: "US Sassuolo",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: "@/assets/logos/Italy - Serie A/US Sassuolo.png",
  },
];
