import type { Team } from "../teams";

export const netherlandsEredivisie: Team[] = [
  {
    id: "ajax",
    name: "Ajax Amsterdam",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Ajax Amsterdam.png",
  },
  {
    id: "az-alkmaar",
    name: "AZ Alkmaar",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/AZ Alkmaar.png",
  },
  {
    id: "excelsior-rotterdam",
    name: "Excelsior Rotterdam",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Excelsior Rotterdam.png",
  },
  {
    id: "fc-groningen",
    name: "FC Groningen",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/FC Groningen.png",
  },
  {
    id: "fc-utrecht",
    name: "FC Utrecht",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/FC Utrecht.png",
  },
  {
    id: "fc-volendam",
    name: "FC Volendam",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/FC Volendam.png",
  },
  {
    id: "feyenoord",
    name: "Feyenoord Rotterdam",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Feyenoord Rotterdam.png",
  },
  {
    id: "fortuna-sittard",
    name: "Fortuna Sittard",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Fortuna Sittard.png",
  },
  {
    id: "go-ahead-eagles",
    name: "Go Ahead Eagles",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Go Ahead Eagles.png",
  },
  {
    id: "heracles-almelo",
    name: "Heracles Almelo",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Heracles Almelo.png",
  },
  {
    id: "nac-breda",
    name: "NAC Breda",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/NAC Breda.png",
  },
  {
    id: "nec-nijmegen",
    name: "NEC Nijmegen",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/NEC Nijmegen.png",
  },
  {
    id: "pec-zwolle",
    name: "PEC Zwolle",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/PEC Zwolle.png",
  },
  {
    id: "psv-eindhoven",
    name: "PSV Eindhoven",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/PSV Eindhoven.png",
  },
  {
    id: "sc-heerenveen",
    name: "SC Heerenveen",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/SC Heerenveen.png",
  },
  {
    id: "sc-telstar",
    name: "SC Telstar",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/SC Telstar.png",
  },
  {
    id: "sparta-rotterdam",
    name: "Sparta Rotterdam",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Sparta Rotterdam.png",
  },
  {
    id: "twente",
    name: "Twente Enschede FC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Netherlands Eredivisie",
    logo: "@/assets/logos/Netherlands - Eredivisie/Twente Enschede FC.png",
  },
];
