import type { Team } from "../teams";

export const norwayEliteserien: Team[] = [
  {
    id: "bryne-fk",
    name: "Bryne FK",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Bryne FK.png",
  },
  {
    id: "bodoglimt",
    name: "FK BodøGlimt",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/FK BodøGlimt.png",
  },
  {
    id: "fk-haugesund",
    name: "FK Haugesund",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/FK Haugesund.png",
  },
  {
    id: "fredrikstad-fk",
    name: "Fredrikstad FK",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Fredrikstad FK.png",
  },
  {
    id: "hamarkameratene",
    name: "Hamarkameratene",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066FF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Hamarkameratene.png",
  },
  {
    id: "kfum-oslo",
    name: "KFUM-Kameratene Oslo",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/KFUM-Kameratene Oslo.png",
  },
  {
    id: "kristiansund-bk",
    name: "Kristiansund BK",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Kristiansund BK.png",
  },
  {
    id: "molde-fk",
    name: "Molde FK",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Molde FK.png",
  },
  {
    id: "rosenborg-bk",
    name: "Rosenborg BK",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Rosenborg BK.png",
  },
  {
    id: "sandefjord-fotball",
    name: "Sandefjord Fotball",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Sandefjord Fotball.png",
  },
  {
    id: "sarpsborg-08",
    name: "Sarpsborg 08 FF",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Sarpsborg 08 FF.png",
  },
  {
    id: "sk-brann",
    name: "SK Brann",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/SK Brann.png",
  },
  {
    id: "stromsgodset-if",
    name: "Strømsgodset IF",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Strømsgodset IF.png",
  },
  {
    id: "tromso-il",
    name: "Tromsø IL",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Tromsø IL.png",
  },
  {
    id: "valerenga-elite",
    name: "Vålerenga Fotball Elite",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Vålerenga Fotball Elite.png",
  },
  {
    id: "viking-fk",
    name: "Viking FK",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Norway Eliteserien",
    logo: "/logos/Norway - Eliteserien/Viking FK.png",
  },
];
