import type { Team } from "../teams";

export const polandEkstraklasa: Team[] = [
  {
    id: "arka-gdynia",
    name: "Arka Gdynia",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Arka Gdynia.png",
  },
  {
    id: "bruk-bet-termalica",
    name: "Bruk-Bet Termalica Nieciecza",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Bruk-Bet Termalica Nieciecza.png",
  },
  {
    id: "cracovia",
    name: "Cracovia",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Cracovia.png",
  },
  {
    id: "gks-katowice",
    name: "GKS Katowice",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/GKS Katowice.png",
  },
  {
    id: "gornik-zabrze",
    name: "Górnik Zabrze",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Górnik Zabrze.png",
  },
  {
    id: "jagiellonia-bialystok",
    name: "Jagiellonia Bialystok",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Jagiellonia Bialystok.png",
  },
  {
    id: "korona-kielce",
    name: "Korona Kielce",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Korona Kielce.png",
  },
  {
    id: "lech-poznan",
    name: "Lech Poznan",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Lech Poznan.png",
  },
  {
    id: "lechia-gdansk",
    name: "Lechia Gdansk",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Lechia Gdansk.png",
  },
  {
    id: "legia-warszawa",
    name: "Legia Warszawa",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Legia Warszawa.png",
  },
  {
    id: "motor-lublin",
    name: "Motor Lublin",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Motor Lublin.png",
  },
  {
    id: "piast-gliwice",
    name: "Piast Gliwice",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Piast Gliwice.png",
  },
  {
    id: "pogon-szczecin",
    name: "Pogon Szczecin",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Pogon Szczecin.png",
  },
  {
    id: "radomiak-radom",
    name: "Radomiak Radom",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Radomiak Radom.png",
  },
  {
    id: "rakow-czestochowa",
    name: "Raków Częstochowa",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Raków Częstochowa.png",
  },
  {
    id: "widzew-lodz",
    name: "Widzew Lodz",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Widzew Lodz.png",
  },
  {
    id: "wisla-plock",
    name: "Wisla Plock",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066FF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Wisla Plock.png",
  },
  {
    id: "zaglebie-lubin",
    name: "Zaglebie Lubin",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Poland PKO BP Ekstraklasa",
    logo: "/logos/Poland - PKO BP Ekstraklasa/Zaglebie Lubin.png",
  },
];
