import type { Team } from "../teams";

export const portugallLigaPortugal: Team[] = [
  {
    id: "avs-futebol",
    name: "Avs Futebol",
    primaryColor: "#1E90FF",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/Avs Futebol.png",
  },
  {
    id: "casa-pia",
    name: "Casa Pia AC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/Casa Pia AC.png",
  },
  {
    id: "cd-nacional",
    name: "CD Nacional",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/CD Nacional.png",
  },
  {
    id: "cd-santa-clara",
    name: "CD Santa Clara",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/CD Santa Clara.png",
  },
  {
    id: "cd-tondela",
    name: "CD Tondela",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/CD Tondela.png",
  },
  {
    id: "cf-estrela-amadora",
    name: "CF Estrela Amadora",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/CF Estrela Amadora.png",
  },
  {
    id: "fc-alverca",
    name: "FC Alverca",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/FC Alverca.png",
  },
  {
    id: "fc-arouca",
    name: "FC Arouca",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/FC Arouca.png",
  },
  {
    id: "famalicao",
    name: "FC Famalicão",
    primaryColor: "#EC1C24",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/FC Famalicão.png",
  },
  {
    id: "porto",
    name: "FC Porto",
    primaryColor: "#003893",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/FC Porto.png",
  },
  {
    id: "estoril",
    name: "GD Estoril Praia",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/GD Estoril Praia.png",
  },
  {
    id: "gil-vicente",
    name: "Gil Vicente FC",
    primaryColor: "#FFCC00",
    secondaryColor: "#000000",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/Gil Vicente FC.png",
  },
  {
    id: "moreirense",
    name: "Moreirense FC",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/Moreirense FC.png",
  },
  {
    id: "rio-ave",
    name: "Rio Ave FC",
    primaryColor: "#008000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/Rio Ave FC.png",
  },
  {
    id: "braga",
    name: "SC Braga",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/SC Braga.png",
  },
  {
    id: "benfica",
    name: "SL Benfica",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/SL Benfica.png",
  },
  {
    id: "sporting",
    name: "Sporting CP",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/Sporting CP.png",
  },
  {
    id: "guimaraes",
    name: "Vitória Guimarães SC",
    primaryColor: "#FFFFFF",
    secondaryColor: "#00A86B",
    league: "Liga Portugal",
    logo: "@/assets/logos/Portugal - Liga Portugal/Vitória Guimarães SC.png",
  },
];
