import type { Team } from "../teams";

export const romaniaSuperLiga: Team[] = [
  {
    id: "acsc-fc-arges",
    name: "ACSC FC Arges",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/ACSC FC Arges.png",
  },
  {
    id: "afc-unirea-slobozia",
    name: "AFC Unirea 04 Slobozia",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/AFC Unirea 04 Slobozia.png",
  },
  {
    id: "afk-csikszereda",
    name: "AFK Csikszereda Miercurea Ciuc",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/AFK Csikszereda Miercurea Ciuc.png",
  },
  {
    id: "cfr-cluj",
    name: "CFR Cluj",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/CFR Cluj.png",
  },
  {
    id: "cs-universitatea-craiova",
    name: "CS Universitatea Craiova",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/CS Universitatea Craiova.png",
  },
  {
    id: "fc-botosani",
    name: "FC Botosani",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FC Botosani.png",
  },
  {
    id: "fc-dinamo",
    name: "FC Dinamo 1948",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FC Dinamo 1948.png",
  },
  {
    id: "fc-hermannstadt",
    name: "FC Hermannstadt",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FC Hermannstadt.png",
  },
  {
    id: "fc-metaloglobus",
    name: "FC Metaloglobus Bucharest",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FC Metaloglobus Bucharest.png",
  },
  {
    id: "fc-rapid",
    name: "FC Rapid 1923",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FC Rapid 1923.png",
  },
  {
    id: "fc-universitatea-cluj",
    name: "FC Universitatea Cluj",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066FF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FC Universitatea Cluj.png",
  },
  {
    id: "fcsb",
    name: "FCSB",
    primaryColor: "#FF0000",
    secondaryColor: "#0066FF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FCSB.png",
  },
  {
    id: "fcv-farul-constanta",
    name: "FCV Farul Constanta",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/FCV Farul Constanta.png",
  },
  {
    id: "petrolul-ploiesti",
    name: "Petrolul Ploiesti",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/Petrolul Ploiesti.png",
  },
  {
    id: "sc-otelul-galati",
    name: "SC Otelul Galati",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/SC Otelul Galati.png",
  },
  {
    id: "uta-arad",
    name: "UTA Arad",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Romania SuperLiga",
    logo: "@/assets/logos/Romania - SuperLiga/UTA Arad.png",
  },
];
