import type { Team } from "../teams";

export const russiaPremierLiga: Team[] = [
  {
    id: "akhmat-grozny",
    name: "Akhmat Grozny",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Akhmat Grozny.png",
  },
  {
    id: "akron-togliatti",
    name: "Akron Togliatti",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Akron Togliatti.png",
  },
  {
    id: "baltika-kaliningrad",
    name: "Baltika Kaliningrad",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066FF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Baltika Kaliningrad.png",
  },
  {
    id: "cska-moscow",
    name: "CSKA Moscow",
    primaryColor: "#FF0000",
    secondaryColor: "#0066CC",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/CSKA Moscow.png",
  },
  {
    id: "dinamo-makhachkala",
    name: "Dinamo Makhachkala",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Dinamo Makhachkala.png",
  },
  {
    id: "dynamo-moscow",
    name: "Dynamo Moscow",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Dynamo Moscow.png",
  },
  {
    id: "fc-krasnodar",
    name: "FC Krasnodar",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/FC Krasnodar.png",
  },
  {
    id: "fc-pari-nizhniy-novgorod",
    name: "FC Pari Nizhniy Novgorod",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/FC Pari Nizhniy Novgorod.png",
  },
  {
    id: "fc-rostov",
    name: "FC Rostov",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/FC Rostov.png",
  },
  {
    id: "fc-sochi",
    name: "FC Sochi",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/FC Sochi.png",
  },
  {
    id: "krylya-sovetov",
    name: "Krylya Sovetov Samara",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Krylya Sovetov Samara.png",
  },
  {
    id: "lokomotiv-moscow",
    name: "Lokomotiv Moscow",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Lokomotiv Moscow.png",
  },
  {
    id: "rubin-kazan",
    name: "Rubin Kazan",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Rubin Kazan.png",
  },
  {
    id: "spartak-moscow",
    name: "Spartak Moscow",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Spartak Moscow.png",
  },
  {
    id: "torpedo-moscow",
    name: "Torpedo Moscow",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Torpedo Moscow.png",
  },
  {
    id: "zenit-spb",
    name: "Zenit St. Petersburg",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Russia Premier Liga",
    logo: "/logos/Russia - Premier Liga/Zenit St. Petersburg.png",
  },
];
