import type { Team } from "../teams";

export const scotlandScottishPremiership: Team[] = [
  {
    id: "aberdeen-fc",
    name: "Aberdeen FC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Aberdeen FC.png",
  },
  {
    id: "celtic-fc",
    name: "Celtic FC",
    primaryColor: "#009900",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Celtic FC.png",
  },
  {
    id: "dundee-fc",
    name: "Dundee FC",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Dundee FC.png",
  },
  {
    id: "dundee-united",
    name: "Dundee United FC",
    primaryColor: "#FF6600",
    secondaryColor: "#000000",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Dundee United FC.png",
  },
  {
    id: "falkirk-fc",
    name: "Falkirk FC",
    primaryColor: "#8B0000",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Falkirk FC.png",
  },
  {
    id: "heart-of-midlothian",
    name: "Heart of Midlothian FC",
    primaryColor: "#8B0000",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Heart of Midlothian FC.png",
  },
  {
    id: "hibernian-fc",
    name: "Hibernian FC",
    primaryColor: "#008000",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Hibernian FC.png",
  },
  {
    id: "kilmarnock-fc",
    name: "Kilmarnock FC",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Kilmarnock FC.png",
  },
  {
    id: "livingston-fc",
    name: "Livingston FC",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Livingston FC.png",
  },
  {
    id: "motherwell-fc",
    name: "Motherwell FC",
    primaryColor: "#8B0000",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Motherwell FC.png",
  },
  {
    id: "rangers-fc",
    name: "Rangers FC",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/Rangers FC.png",
  },
  {
    id: "st-mirren-fc",
    name: "St. Mirren FC",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Scotland Scottish Premiership",
    logo: "@/assets/logos/Scotland - Scottish Premiership/St. Mirren FC.png",
  },
];
