import type { Team } from "../teams";

export const serbiaSuperLiga: Team[] = [
  {
    id: "fk-cukaricki",
    name: "FK Cukaricki",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Cukaricki.png",
  },
  {
    id: "fk-imt-belgrad",
    name: "FK IMT Belgrad",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK IMT Belgrad.png",
  },
  {
    id: "fk-javor-matis",
    name: "FK Javor-Matis Ivanjica",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Javor-Matis Ivanjica.png",
  },
  {
    id: "fk-mladost-lucani",
    name: "FK Mladost Lucani",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066FF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Mladost Lucani.png",
  },
  {
    id: "fk-napredak-krusevac",
    name: "FK Napredak Krusevac",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Napredak Krusevac.png",
  },
  {
    id: "fk-novi-pazar",
    name: "FK Novi Pazar",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Novi Pazar.png",
  },
  {
    id: "partizan-belgrade",
    name: "FK Partizan Belgrade",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Partizan Belgrade.png",
  },
  {
    id: "radnicki-1923",
    name: "FK Radnicki 1923 Kragujevac",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Radnicki 1923 Kragujevac.png",
  },
  {
    id: "radnicki-nis",
    name: "FK Radnicki Nis",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Radnicki Nis.png",
  },
  {
    id: "radnik-surdulica",
    name: "FK Radnik Surdulica",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Radnik Surdulica.png",
  },
  {
    id: "spartak-subotica",
    name: "FK Spartak Subotica",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Spartak Subotica.png",
  },
  {
    id: "fk-tsc-backa-topola",
    name: "FK TSC Backa Topola",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066FF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK TSC Backa Topola.png",
  },
  {
    id: "fk-vojvodina",
    name: "FK Vojvodina Novi Sad",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/FK Vojvodina Novi Sad.png",
  },
  {
    id: "ofk-beograd",
    name: "OFK Beograd",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/OFK Beograd.png",
  },
  {
    id: "red-star-belgrade",
    name: "Red Star Belgrade",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/Red Star Belgrade.png",
  },
  {
    id: "zeleznicar-pancevo",
    name: "Zeleznicar Pancevo",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Serbia Super liga Srbije",
    logo: "@/assets/logos/Serbia - Super liga Srbije/Zeleznicar Pancevo.png",
  },
];
