import type { Team } from "../teams";

export const spainLaLiga: Team[] = [
  {
    id: "athletic-bilbao",
    name: "Athletic Bilbao",
    primaryColor: "#DC0000",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Athletic Bilbao.png",
  },
  {
    id: "atletico-madrid",
    name: "Atlético de Madrid",
    primaryColor: "#CE3524",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Atlético de Madrid.png",
  },
  {
    id: "ca-osasuna",
    name: "CA Osasuna",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/CA Osasuna.png",
  },
  {
    id: "celta-vigo",
    name: "Celta de Vigo",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Celta de Vigo.png",
  },
  {
    id: "deportivo-alaves",
    name: "Deportivo Alavés",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Deportivo Alavés.png",
  },
  {
    id: "elche-cf",
    name: "Elche CF",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Elche CF.png",
  },
  {
    id: "barcelona",
    name: "FC Barcelona",
    primaryColor: "#A50044",
    secondaryColor: "#004D98",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/FC Barcelona.png",
  },
  {
    id: "getafe-cf",
    name: "Getafe CF",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Getafe CF.png",
  },
  {
    id: "girona-fc",
    name: "Girona FC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Girona FC.png",
  },
  {
    id: "levante-ud",
    name: "Levante UD",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Levante UD.png",
  },
  {
    id: "rayo-vallecano",
    name: "Rayo Vallecano",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Rayo Vallecano.png",
  },
  {
    id: "rcd-espanyol",
    name: "RCD Espanyol Barcelona",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/RCD Espanyol Barcelona.png",
  },
  {
    id: "rcd-mallorca",
    name: "RCD Mallorca",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/RCD Mallorca.png",
  },
  {
    id: "real-betis",
    name: "Real Betis Balompié",
    primaryColor: "#FFFFFF",
    secondaryColor: "#00A651",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Real Betis Balompié.png",
  },
  {
    id: "real-madrid",
    name: "Real Madrid",
    primaryColor: "#FFFFFF",
    secondaryColor: "#00529F",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Real Madrid.png",
  },
  {
    id: "real-oviedo",
    name: "Real Oviedo",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Real Oviedo.png",
  },
  {
    id: "real-sociedad",
    name: "Real Sociedad",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Real Sociedad.png",
  },
  {
    id: "sevilla",
    name: "Sevilla FC",
    primaryColor: "#FFFFFF",
    secondaryColor: "#D4021D",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Sevilla FC.png",
  },
  {
    id: "valencia",
    name: "Valencia CF",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF8C00",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Valencia CF.png",
  },
  {
    id: "villarreal",
    name: "Villarreal CF",
    primaryColor: "#FFD000",
    secondaryColor: "#000000",
    league: "La Liga",
    logo: "/logos/Spain - LaLiga/Villarreal CF.png",
  },
];
