import type { Team } from "../teams";

export const swedenAllsvenskan: Team[] = [
  {
    id: "aik",
    name: "AIK",
    primaryColor: "#000000",
    secondaryColor: "#FFD700",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/AIK.png",
  },
  {
    id: "bk-hacken",
    name: "BK Häcken",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/BK Häcken.png",
  },
  {
    id: "degerfors-if",
    name: "Degerfors IF",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/Degerfors IF.png",
  },
  {
    id: "djurgardens-if",
    name: "Djurgårdens IF",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/Djurgårdens IF.png",
  },
  {
    id: "gais",
    name: "GAIS",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/GAIS.png",
  },
  {
    id: "halmstads-bk",
    name: "Halmstads BK",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/Halmstads BK.png",
  },
  {
    id: "hammarby-if",
    name: "Hammarby IF",
    primaryColor: "#0066CC",
    secondaryColor: "#FF0000",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/Hammarby IF.png",
  },
  {
    id: "if-brommapojkarna",
    name: "IF Brommapojkarna",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/IF Brommapojkarna.png",
  },
  {
    id: "if-elfsborg",
    name: "IF Elfsborg",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/IF Elfsborg.png",
  },
  {
    id: "ifk-goteborg",
    name: "IFK Göteborg",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/IFK Göteborg.png",
  },
  {
    id: "ifk-norrkoping",
    name: "IFK Norrköping",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/IFK Norrköping.png",
  },
  {
    id: "ifk-varnamo",
    name: "IFK Värnamo",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/IFK Värnamo.png",
  },
  {
    id: "ik-sirius",
    name: "IK Sirius",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/IK Sirius.png",
  },
  {
    id: "malmo-ff",
    name: "Malmö FF",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/Malmö FF.png",
  },
  {
    id: "mjalby-aif",
    name: "Mjällby AIF",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/Mjällby AIF.png",
  },
  {
    id: "osters-if",
    name: "Östers IF",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Sweden Allsvenskan",
    logo: "/logos/Sweden - Allsvenskan/Östers IF.png",
  },
];
