import type { Team } from "../teams";

export const switzerlandSuperLeague: Team[] = [
  {
    id: "bsc-young-boys",
    name: "BSC Young Boys",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/BSC Young Boys.png",
  },
  {
    id: "fc-basel",
    name: "FC Basel 1893",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Basel 1893.png",
  },
  {
    id: "fc-lausanne-sport",
    name: "FC Lausanne-Sport",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Lausanne-Sport.png",
  },
  {
    id: "fc-lugano",
    name: "FC Lugano",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Lugano.png",
  },
  {
    id: "fc-luzern",
    name: "FC Luzern",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Luzern.png",
  },
  {
    id: "fc-sion",
    name: "FC Sion",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Sion.png",
  },
  {
    id: "fc-st-gallen",
    name: "FC St. Gallen 1879",
    primaryColor: "#008000",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC St. Gallen 1879.png",
  },
  {
    id: "fc-thun",
    name: "FC Thun",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Thun.png",
  },
  {
    id: "fc-winterthur",
    name: "FC Winterthur",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Winterthur.png",
  },
  {
    id: "fc-zurich",
    name: "FC Zürich",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/FC Zürich.png",
  },
  {
    id: "grasshopper-club",
    name: "Grasshopper Club Zurich",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/Grasshopper Club Zurich.png",
  },
  {
    id: "servette-fc",
    name: "Servette FC",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Switzerland Super League",
    logo: "@/assets/logos/Switzerland - Super League/Servette FC.png",
  },
];
