import type { Team } from "../teams";

export const turkiyeSuperLig: Team[] = [
  {
    id: "alanyaspor",
    name: "Alanyaspor",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Alanyaspor.png",
  },
  {
    id: "antalyaspor",
    name: "Antalyaspor",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Antalyaspor.png",
  },
  {
    id: "basaksehir-fk",
    name: "Basaksehir FK",
    primaryColor: "#0066FF",
    secondaryColor: "#FF6600",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Basaksehir FK.png",
  },
  {
    id: "besiktas-jk",
    name: "Besiktas JK",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Besiktas JK.png",
  },
  {
    id: "caykur-rizespor",
    name: "Caykur Rizespor",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Caykur Rizespor.png",
  },
  {
    id: "eyupspor",
    name: "Eyüpspor",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Eyüpspor.png",
  },
  {
    id: "fatih-karagumruk",
    name: "Fatih Karagümrük",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Fatih Karagümrük.png",
  },
  {
    id: "fenerbahce",
    name: "Fenerbahce",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Fenerbahce.png",
  },
  {
    id: "galatasaray",
    name: "Galatasaray",
    primaryColor: "#FF0000",
    secondaryColor: "#FFD700",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Galatasaray.png",
  },
  {
    id: "gaziantep-fk",
    name: "Gaziantep FK",
    primaryColor: "#FF0000",
    secondaryColor: "#000000",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Gaziantep FK.png",
  },
  {
    id: "genclerbirligi",
    name: "Genclerbirligi Ankara",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Genclerbirligi Ankara.png",
  },
  {
    id: "goztepe",
    name: "Göztepe",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Göztepe.png",
  },
  {
    id: "kasimpasa",
    name: "Kasimpasa",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Kasimpasa.png",
  },
  {
    id: "kayserispor",
    name: "Kayserispor",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Kayserispor.png",
  },
  {
    id: "kocaelispor",
    name: "Kocaelispor",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Kocaelispor.png",
  },
  {
    id: "konyaspor",
    name: "Konyaspor",
    primaryColor: "#008000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Konyaspor.png",
  },
  {
    id: "samsunspor",
    name: "Samsunspor",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Samsunspor.png",
  },
  {
    id: "trabzonspor",
    name: "Trabzonspor",
    primaryColor: "#8B0000",
    secondaryColor: "#FFFFFF",
    league: "Türkiye Süper Lig",
    logo: "/logos/Türkiye - Süper Lig/Trabzonspor.png",
  },
];
