import type { Team } from "../teams";

export const ukrainePremierLiga: Team[] = [
  {
    id: "dynamo-kyiv",
    name: "Dynamo Kyiv",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Dynamo Kyiv.png",
  },
  {
    id: "epicentr-kamyanets",
    name: "Epicentr Kamyanets-Podilskyi",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Epicentr Kamyanets-Podilskyi.png",
  },
  {
    id: "fc-kudrivka",
    name: "FC Kudrivka",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/FC Kudrivka.png",
  },
  {
    id: "fc-oleksandriya",
    name: "FC Oleksandriya",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/FC Oleksandriya.png",
  },
  {
    id: "karpaty-lviv",
    name: "Karpaty Lviv",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Karpaty Lviv.png",
  },
  {
    id: "kolos-kovalivka",
    name: "Kolos Kovalivka",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Kolos Kovalivka.png",
  },
  {
    id: "kryvbas-kryvyi-rig",
    name: "Kryvbas Kryvyi Rig",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Kryvbas Kryvyi Rig.png",
  },
  {
    id: "lnz-cherkasy",
    name: "LNZ Cherkasy",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/LNZ Cherkasy.png",
  },
  {
    id: "metalist-kharkiv",
    name: "Metalist 1925 Kharkiv",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Metalist 1925 Kharkiv.png",
  },
  {
    id: "nk-veres-rivne",
    name: "NK Veres Rivne",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/NK Veres Rivne.png",
  },
  {
    id: "obolon-kyiv",
    name: "Obolon Kyiv",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Obolon Kyiv.png",
  },
  {
    id: "polissya-zhytomyr",
    name: "Polissya Zhytomyr",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Polissya Zhytomyr.png",
  },
  {
    id: "rukh-lviv",
    name: "Rukh Lviv",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Rukh Lviv.png",
  },
  {
    id: "sc-poltava",
    name: "SC Poltava",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/SC Poltava.png",
  },
  {
    id: "shakhtar-donetsk",
    name: "Shakhtar Donetsk",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Shakhtar Donetsk.png",
  },
  {
    id: "zorya-lugansk",
    name: "Zorya Lugansk",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "Ukraine Premier Liga",
    logo: "@/assets/logos/Ukraine - Premier Liga/Zorya Lugansk.png",
  },
];
