-- Enable RLS on tables
ALTER TABLE public.jerseys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jersey_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
